### ISSUE TITLE
easy use api

### ISSUE THREAD

**Issue by cdhx** [princeton-vl/attach-juxtapose-parser#2]
Thanks for publish this work, I wonder is there any way to easy use this method without deploy the whole project, such as python package, API or online demo?

**Comment by yangky11** [comment]
Thank you for your interest in our project. You can parse your own texts following the instructions [here](https://github.com/princeton-vl/attach-juxtapose-parser#parsing-user-provided-texts), but it requires you to deploy the whole project.

It would be great to have more straightforward APIs (e.g., integration with Spacy or NLTK), but unfortunately, I do not have enough bandwidth to work on it at this moment. I'll leave this issue open, and contributions from anyone are welcomed.

**Comment by yangky11** [comment]
I'm closing this issue since we have a third-party implementation with possibly easier to use APIs ([SuPar](https://github.com/yzhangcs/parser)).
