### ISSUE TITLE
How to parse pre-tokenized text?

### ISSUE THREAD

**Issue by Caz-T** [princeton-vl/attach-juxtapose-parser#3]
Hi,
I'm primarily interested in parsing already tokenized (but not pos-tagged) text using the ctb-bert-graph.pth model. I might need some help, if possible, in editing the parse.py text so that i could use my tokenization. Or maybe there's another way to do such tasks? Your assistance would be of great help for me.

**Comment by yangky11** [comment]
Hi,

Thanks for your interest in our work. We use Spacy for tokenization and POS tagging. It should be possible to plug in your own tokenization and tagging in the `__init__` function of `UserProvidedTexts`. Though I'm not sure if that will impact the performance. If so, you may need to re-train the model using your tokenization and tagging.
https://github.com/princeton-vl/attach-juxtapose-parser/blob/20e0ebb1bf43fc69b6a4c46a54bb0362fc062eed/parse.py#L31

**Comment by Caz-T** [comment]
Hi, 
Thanks for the answer! Will try it out soon.
